server {
    listen 80;
    server_name sail3-api.eu-north-1.elasticbeanstalk.com sail3-api-stage.eu-north-1.elasticbeanstalk.com;

    location / {
        proxy_pass http://host.docker.internal:5095;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }
}
